name: CD Pipeline for Frontend

on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.organization=sparkotto \
            -Dsonar.projectKey=SparkOtto_sparkotto-front \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

  security:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          exit-code: "0"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Run File System Scan
        run: trivy fs --exit-code 1 --severity CRITICAL,HIGH .

  deploy:
    name: Deploy to Portainer (Frontend)
    runs-on: ubuntu-latest
    needs: [sonar, security]
    steps:
      - name: Trigger Portainer webhook
        run: |
          curl -X POST "https://195.15.222.167:9443/api/stacks/webhooks/${{ secrets.TOKEN_GIT_FRONT }}" --insecure
